# coding=utf-8
"""
Django settings for HimalayaMultimediaDatabase project.

Generated by 'django-admin startproject' using Django 1.8.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
import xadmin

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wl4l(rkx5p5sx%lqu8n-!20nu58#)9idto#v3t*r!211li6a8i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['192.168.137.185']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # add app
    'xadmin',
    'crispy_forms',
    'reversion',

    'bootstrap3',
    'haystack',
    'apps.himalaya',

    # 分页控制 start
    'pagination',
    # 分页控制 end

    'rest_framework',
    'django_ajax',
    'apps.himalaya.templatetags'


)

MIDDLEWARE_CLASSES = (
    'apps.himalaya.middleware.HaystackBatchFlushMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # 分页控制
    'pagination.middleware.PaginationMiddleware',
)

ROOT_URLCONF = 'HimalayaMultimediaDatabase.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #分页代码
                # 'django.core.context_processors.auth',
                'django.contrib.auth.context_processors.auth',
                'django.core.context_processors.debug',
                'django.core.context_processors.i18n',
                'django.core.context_processors.media',
                'django.core.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'HimalayaMultimediaDatabase.wsgi.application'
PAGINATION_DEFAULT_WINDOW = 3

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
#    'default': {
#            'ENGINE': 'django.db.backends.sqlite3',
#            'NAME': os.path.join(BASE_DIR, 'xmlydb.sqlite3'),
#       },
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'new',
        'USER': 'postgres',
        'PASSWORD': '123456',
        # 'HOST': '192.168.137.1',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
#         'NAME': 'himalaya',                      # Or path to database file if using sqlite3.
#         # The following settings are not used with sqlite3:
#         'USER': 'himalaya',
#         'PASSWORD': 'nlp422',
#         'HOST': '202.115.52.17',                      # Empty for localhost through domain sockets or '127.0.0.1' for localhost through TCP.
#         'PORT': '3306',                      # Set to empty string for default.
#     }
# }

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static_copy")

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    # '/home/knight/XMLY_0826_demo/XMLY_8_4_demo/static/',
    '/media/bella/0C2CB0012CAFE3C4/ximalaya-server/XMLY_8_4_demo/static/',
)


 #haystack setting
# import os
# HAYSTACK_CONNECTIONS = {
#     'default': {
#         'ENGINE': 'apps.himadatabase.whoosh_cn_backend.WhooshEngine',
#         'PATH': os.path.join(os.path.dirname(__file__), 'whoosh_index'),
#     },
# }
HAYSTACK_CUSTOM_HIGHLIGHTER = 'apps.himalaya.search_utils.MyHighlighter'
#HAYSTACK settings

# HAYSTACK_SIGNAL_PROCESSOR = 'apps.himalaya.signals.BatchingSignalProcessor'
# HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
HAYSTACK_SIGNAL_PROCESSOR = 'apps.himalaya.signals.RelatedRealtimeSignalProcessor'
# HAYSTACK_SIGNAL_PROCESSOR = 'apps.himalaya.signals.lanM2MSignalProcessor'
# HAYSTACK_SEARCH_RESULTS_PER_PAGE = 12
# HAYSTACK_CONNECTIONS = {
#         'default': {
#             'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
#             'URL': 'http://127.0.0.1:9200/',
#             'INDEX_NAME': 'haystack',
#         },
# }



HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
        'URL': 'http://127.0.0.1:8983/solr',
        'TIMEOUT': 500,
        'INDEX_NAME': 'haystack',
        # ...or for multicore...
        # 'URL': 'http://127.0.0.1:8983/solr/mysite',
    },
}



# index update
# HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
# 媒体文件，上传文件，上传图片存放位置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CACHES = {
    'default':{
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATIOIN': '202.115.52.55:8080',
    }
}

