# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftNum', models.IntegerField()),
                ('rightNum', models.IntegerField()),
                ('path', models.CharField(max_length=100)),
                ('attrName', models.CharField(max_length=50, verbose_name='\u5c5e\u6027\u540d\u79f0')),
                ('sortNum', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='himalaya.Category')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b\u5c5e\u6027',
                'verbose_name_plural': '\u5206\u7c7b\u5c5e\u6027',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplineTypeName', models.CharField(max_length=50, unique=True, verbose_name='\u7c7b\u578b\u540d\u79f0')),
                ('sortNum', models.IntegerField(blank=True, default=0, verbose_name='\u6392\u5e8f')),
            ],
            options={
                'verbose_name': '\u5b66\u79d1\u7c7b\u578b',
                'verbose_name_plural': '\u5b66\u79d1\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='FileBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filecode', models.CharField(blank=True, max_length=30, verbose_name='\u6587\u732e\u7f16\u53f7')),
                ('title', models.CharField(max_length=200, verbose_name='\u6587\u732e\u540d\u79f0')),
                ('creator', models.CharField(max_length=300, verbose_name='\u4f5c\u8005/\u7f16\u8005')),
                ('keywords', models.CharField(help_text='\u5173\u952e\u8bcd\u8bf7\u7528\u5206\u53f7\uff08\uff1b\uff09\u9694\u5f00', max_length=100, verbose_name='\u5173\u952e\u8bcd')),
                ('description', models.TextField(blank=True, verbose_name='\u5185\u5bb9\u7b80\u4ecb')),
                ('publisher', models.CharField(max_length=200, verbose_name='\u6765\u6e90')),
                ('contributor', models.CharField(blank=True, max_length=200, verbose_name='\u8bd1\u8005/\u6821\u8ba2\u8005')),
                ('size', models.CharField(blank=True, default=30, editable=False, max_length=30, verbose_name='\u6587\u4ef6\u5927\u5c0f')),
                ('pubDate', models.DateField(verbose_name='\u51fa\u7248\u65f6\u95f4')),
                ('contentLength', models.IntegerField(blank=True, default=0, verbose_name='\u9875\u6570')),
                ('uploadPeople', models.CharField(max_length=50, verbose_name='\u6587\u4ef6\u4e0a\u4f20\u4eba')),
                ('uploadDate', models.DateField(auto_now=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('updateDate', models.DateField(auto_now_add=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
                ('picture', models.ImageField(upload_to='himalaya/images', verbose_name='\u7f29\u7565\u56fe')),
                ('attachment', models.FileField(upload_to='himalaya/files', verbose_name='\u9644  \u4ef6')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='\u5907\u6ce8')),
                ('check', models.BooleanField(default=False, max_length=1, verbose_name='\u662f\u5426\u5ba1\u6838')),
                ('subjecttype', models.IntegerField(default=-1, editable=False, verbose_name='\u4e13\u9898\u7c7b\u578b')),
                ('discipline', models.ManyToManyField(help_text='\u591a\u9009\u6309Ctril\u952e', to='himalaya.Discipline', verbose_name='\u5b66  \u79d1')),
            ],
            options={
                'verbose_name': '\u6587\u732e\u57fa\u7840\u5c5e\u6027',
                'verbose_name_plural': '\u6587\u732e\u57fa\u7840\u5c5e\u6027',
            },
        ),
        migrations.CreateModel(
            name='FileExtendInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileId', models.IntegerField(editable=False, verbose_name='\u6587\u732e\u7f16\u53f7')),
                ('fieldId', models.IntegerField(editable=False, verbose_name='\u6587\u732e\u5c5e\u6027\u7f16\u53f7')),
                ('filedValue', models.CharField(max_length=100, verbose_name='\u5c5e\u6027\u503c')),
            ],
            options={
                'verbose_name': '\u4e13\u9898\u6587\u732e\u5e93',
                'verbose_name_plural': '\u4e13\u9898\u6587\u732e\u5e93',
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileTypeName', models.CharField(max_length=50, verbose_name='\u7c7b\u578b\u540d\u79f0')),
                ('sortNum', models.IntegerField(blank=True, default=0, verbose_name='\u6392\u5e8f')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6\u7c7b\u578b',
                'verbose_name_plural': '\u6587\u4ef6\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatTypeName', models.CharField(max_length=50, unique=True, verbose_name='\u7c7b\u578b\u540d\u79f0')),
                ('sortNum', models.IntegerField(blank=True, default=0, verbose_name='\u6392\u5e8f')),
            ],
            options={
                'verbose_name': '\u683c\u5f0f\u7c7b\u578b',
                'verbose_name_plural': '\u683c\u5f0f\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanTypeName', models.CharField(max_length=50, unique=True, verbose_name='\u7c7b\u578b\u540d\u79f0')),
                ('sortNum', models.IntegerField(blank=True, default=0, verbose_name='\u6392\u5e8f')),
            ],
            options={
                'verbose_name': '\u8bed\u8a00',
                'verbose_name_plural': '\u8bed\u8a00',
            },
        ),
        migrations.CreateModel(
            name='SpaceScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spcaeTypeName', models.CharField(max_length=50, unique=True, verbose_name='\u7c7b\u578b\u540d\u79f0')),
                ('sortNum', models.IntegerField(blank=True, default=0, verbose_name='\u6392\u5e8f')),
            ],
            options={
                'verbose_name': '\u7a7a\u95f4\u8303\u56f4',
                'verbose_name_plural': '\u7a7a\u95f4\u8303\u56f4',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=50, verbose_name='\u4e13\u9898\u540d\u79f0')),
                ('subjectDescribe', models.TextField(help_text='\u6700\u591a\u8f93\u5165100\u5b57', max_length=100, verbose_name='\u4e13\u9898\u63cf\u8ff0')),
                ('subjectPic', models.ImageField(upload_to='himalaya/images', verbose_name='\u7f29\u7565\u56fe')),
                ('subjectDate', models.DateField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6587\u732e\u4e13\u9898',
                'verbose_name_plural': '\u6587\u732e\u4e13\u9898',
            },
        ),
        migrations.CreateModel(
            name='SubjectTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=50, verbose_name='\u5c5e\u6027\u540d\u79f0')),
                ('fieldType', models.CharField(max_length=50, verbose_name='\u5c5e\u6027\u7c7b\u578b')),
                ('isPrompt', models.BooleanField(verbose_name='\u662f\u5426\u63d0\u793a')),
                ('promtInfo', models.CharField(max_length=100, verbose_name='\u63d0\u793a\u4fe1\u606f')),
                ('isMust', models.BooleanField(verbose_name='\u662f\u5426\u5fc5\u586b')),
                ('corrAttri', models.IntegerField(verbose_name='\u5173\u8054\u5206\u7c7b\u5c5e\u6027')),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='himalaya.Subject', verbose_name='\u6240\u5c5e\u4e13\u9898')),
            ],
            options={
                'verbose_name': '\u4e13\u9898\u6587\u732e\u5c5e\u6027',
                'verbose_name_plural': '\u4e13\u9898\u6587\u732e\u5c5e\u6027',
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewName', models.CharField(max_length=100, verbose_name='\u5168\u666f\u540d\u79f0')),
                ('createDate', models.DateField(verbose_name='\u62cd\u6444\u65e5\u671f')),
                ('viewIntro', models.TextField(help_text='\u6700\u591a\u8f93\u5165100\u5b57', max_length=100, verbose_name='\u7b80  \u4ecb')),
                ('viewPic', models.ImageField(upload_to='himalaya/images', verbose_name='\u7f29\u7565\u56fe')),
                ('viewAuth', models.CharField(max_length=100, verbose_name='\u62cd  \u6444')),
                ('viewPlace', models.CharField(max_length=100, verbose_name='\u5730  \u70b9')),
                ('viewEqu', models.CharField(max_length=200, verbose_name='\u5236  \u4f5c')),
                ('viewPath', models.FileField(upload_to='himalaya/quanjing', verbose_name='\u6587\u4ef6\u8def\u5f84')),
            ],
            options={
                'verbose_name': '\u5168\u666f',
                'verbose_name_plural': '\u5168\u666f',
            },
        ),
        migrations.AddField(
            model_name='filebaseinfo',
            name='fileFormat',
            field=models.ManyToManyField(help_text='\u591a\u9009\u6309Ctril\u952e', to='himalaya.Format', verbose_name='\u683c\u5f0f'),
        ),
        migrations.AddField(
            model_name='filebaseinfo',
            name='fileType',
            field=models.ManyToManyField(help_text='\u591a\u9009\u6309Ctril\u952e', to='himalaya.FileType', verbose_name='\u6587\u4ef6\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='filebaseinfo',
            name='language',
            field=models.ManyToManyField(help_text='\u591a\u9009\u6309Ctril\u952e', to='himalaya.Language', verbose_name='\u8bed  \u8a00'),
        ),
        migrations.AddField(
            model_name='filebaseinfo',
            name='spatial',
            field=models.ManyToManyField(help_text='\u591a\u9009\u6309Ctril\u952e', to='himalaya.SpaceScope', verbose_name='\u7a7a\u95f4\u8303\u56f4'),
        ),
    ]
