# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himalaya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttheme',
            name='corrAttri',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5173\u8054\u5206\u7c7b\u5c5e\u6027'),
        ),
    ]
