# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himalaya', '0002_auto_20160803_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttheme',
            name='promtInfo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63d0\u793a\u4fe1\u606f'),
        ),
    ]
