# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himalaya', '0004_auto_20160803_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sortNum',
            field=models.IntegerField(default=0, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='sortNum',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='check',
            field=models.BooleanField(default=False, max_length=1, verbose_name='\u662f\u5426\u5ba1\u6838'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='sortNum',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='format',
            name='sortNum',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='language',
            name='sortNum',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='spacescope',
            name='sortNum',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u6392\u5e8f'),
        ),
    ]
