# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himalaya', '0007_auto_20160803_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebaseinfo',
            name='check',
            field=models.BooleanField(default=True, max_length=1, verbose_name='\u662f\u5426\u5ba1\u6838'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='sortNum',
            field=models.IntegerField(blank=True, default=0, unique=True, verbose_name='\u6392\u5e8f'),
        ),
    ]
