# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himalaya', '0008_auto_20160803_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetype',
            name='fileTypeName',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u7c7b\u578b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='sortNum',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u6392\u5e8f'),
        ),
    ]
