# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himalaya', '0010_auto_20160803_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='sortNum',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='sortNum',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='format',
            name='sortNum',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='language',
            name='sortNum',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='spacescope',
            name='sortNum',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='\u6392\u5e8f'),
        ),
    ]
