# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himalaya', '0011_auto_20160804_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebaseinfo',
            name='updateDate',
            field=models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='uploadDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4'),
        ),
    ]
