# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himalaya', '0015_auto_20161005_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebaseinfo',
            name='contentLength',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u9875\u6570'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='contributor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8bd1\u8005/\u6821\u8ba2\u8005'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='filecode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6587\u732e\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='size',
            field=models.CharField(blank=True, default=30, editable=False, max_length=30, null=True, verbose_name='\u6587\u4ef6\u5927\u5c0f'),
        ),
    ]
