# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himalaya', '0016_auto_20161005_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebaseinfo',
            name='contributor',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u8bd1\u8005/\u6821\u8ba2\u8005'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='creator',
            field=models.CharField(blank=True, max_length=300, verbose_name='\u4f5c\u8005/\u7f16\u8005'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='description',
            field=models.TextField(blank=True, verbose_name='\u5185\u5bb9\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='discipline',
            field=models.ManyToManyField(blank=True, help_text='\u591a\u9009\u6309Ctril\u952e', to='himalaya.Discipline', verbose_name='\u5b66  \u79d1'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='fileFormat',
            field=models.ManyToManyField(blank=True, help_text='\u591a\u9009\u6309Ctril\u952e', to='himalaya.Format', verbose_name='\u683c\u5f0f'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='fileType',
            field=models.ManyToManyField(blank=True, help_text='\u591a\u9009\u6309Ctril\u952e', to='himalaya.FileType', verbose_name='\u6587\u4ef6\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='filecode',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u6587\u732e\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='keywords',
            field=models.CharField(blank=True, help_text='\u5173\u952e\u8bcd\u8bf7\u7528\u5206\u53f7\uff08\uff1b\uff09\u9694\u5f00', max_length=100, verbose_name='\u5173\u952e\u8bcd'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='language',
            field=models.ManyToManyField(blank=True, help_text='\u591a\u9009\u6309Ctril\u952e', to='himalaya.Language', verbose_name='\u8bed  \u8a00'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='notes',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u6765\u6e90'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='size',
            field=models.CharField(blank=True, default=30, editable=False, max_length=30, verbose_name='\u6587\u4ef6\u5927\u5c0f'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='spatial',
            field=models.ManyToManyField(blank=True, help_text='\u591a\u9009\u6309Ctril\u952e', to='himalaya.SpaceScope', verbose_name='\u7a7a\u95f4\u8303\u56f4'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='uploadPeople',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u6587\u4ef6\u4e0a\u4f20\u4eba'),
        ),
    ]
