# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-26 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himalaya', '0021_auto_20170406_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='Publication',
            field=models.CharField(blank=True, help_text='\u6e38\u8bb0\u520a\u767b\u520a\u7269', max_length=1000, null=True, verbose_name='\u520a\u7269/\u6c47\u7f16'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='author',
            field=models.CharField(blank=True, help_text='\u4e66\u76ee\u4f5c\u8005', max_length=1000, null=True, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='bNameCH',
            field=models.CharField(blank=True, help_text='\u8457\u4f5c\u4e2d\u6587\u540d\u79f0', max_length=1000, null=True, verbose_name='\u8457\u4f5c\u540d\u79f0\uff08CH\uff09'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='bNameEN',
            field=models.CharField(blank=True, help_text='\u8457\u4f5c\u82f1\u6587\u540d\u79f0', max_length=1000, null=True, verbose_name='\u8457\u4f5c\u540d\u79f0\uff08EN\uff09'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='bookID',
            field=models.CharField(help_text='\u4e66\u76eeID,\u4e2d\u6587\u6e38\u8bb0\u4ee51\u5f00\u5934,\u81ea1001\u5f00\u59cb;\u5916\u6587\u6e38\u8bb0\u4ee52\u5f00\u5934,\u4ee52001\u5f00\u59cb', max_length=30, primary_key=True, serialize=False, verbose_name='\u4e66\u76eeID'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='dopub',
            field=models.CharField(blank=True, help_text='\u520a\u767b\u671f\u520a\u65e5\u671f', max_length=1000, null=True, verbose_name='\u520a\u7269\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='nationality',
            field=models.CharField(blank=True, help_text='\u4f5c\u8005\u56fd\u522b', max_length=1000, null=True, verbose_name='\u4f5c\u8005\u56fd\u522b'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='notes',
            field=models.TextField(blank=True, help_text='\u6982\u8ff0\u4f5c\u8005\u6e38\u5386\u539f\u56e0', null=True, verbose_name='\u9898\u89e3'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='pageNum',
            field=models.CharField(help_text='\u6240\u5728\u520a\u7269\u7684\u9875\u7801', max_length=1000, null=True, verbose_name='\u6240\u5728\u520a\u7269/\u6c47\u7f16\u9875\u7801'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='press',
            field=models.CharField(blank=True, help_text='\u8457\u4f5c\u51fa\u7248\u793e', max_length=2000, null=True, verbose_name='\u51fa\u7248\u793e'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='pubdate',
            field=models.CharField(blank=True, help_text='\u51fa\u7248\u65e5\u671f', max_length=1000, null=True, verbose_name='\u51fa\u7248\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='translator',
            field=models.CharField(blank=True, help_text='\u8bd1\u8005\u59d3\u540d', max_length=1000, null=True, verbose_name='\u8bd1\u8005'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='subjecttype',
            field=models.IntegerField(default=-1, editable=False, verbose_name='\u4e13\u9898\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='route',
            name='RouteName',
            field=models.CharField(max_length=1000, null=True, verbose_name='\u7ebf\u8def\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='route',
            name='RoutePer',
            field=models.CharField(max_length=1000, null=True, verbose_name='\u6e38\u5386\u4eba'),
        ),
        migrations.AlterField(
            model_name='route',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='\u9898\u89e3'),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='\u7eac\u5ea6'),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='\u7ecf\u5ea6'),
        ),
        migrations.AlterField(
            model_name='site',
            name='sitenameCH',
            field=models.CharField(max_length=1000, null=True, verbose_name='\u5730\u70b9'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='DataPage',
            field=models.CharField(blank=True, help_text='\u4fe1\u606f\u6240\u5728\u7684\u9875\u7801', max_length=100, null=True, verbose_name='\u6570\u636e\u9875\u7801'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='agriculture',
            field=models.TextField(blank=True, help_text='\u519c\u4e1a\u60c5\u51b5', null=True, verbose_name='\u6e38\u5386\u5730\u519c\u4e1a'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='custom',
            field=models.TextField(blank=True, help_text='\u5a5a\u4e27\u793c\u4eea\u3001\u5de5\u827a\u6587\u5316\u3001\u88c5\u9970\u6587\u5316\u3001\u996e\u98df\u6587\u5316\u3001\u8282\u65e5\u6587\u5316\u3001\u620f\u66f2\u6587\u5316\u3001\u6b4c\u821e\u6587\u5316\u3001\u7ed8\u753b\u6587\u5316\u3001\u97f3\u4e50\u6587\u5316\u3001\u5236\u4f5c\u6587\u5316\u7b49', null=True, verbose_name='\u98ce\u4fd7\u6587\u5316'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='economy',
            field=models.TextField(blank=True, help_text='\u7ecf\u6d4e\u8d38\u6613\u3001\u77ff\u4ea7\u3001\u96c6\u5e02\u7b49\u60c5\u51b5', null=True, verbose_name='\u6e38\u5386\u5730\u7ecf\u6d4e'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='education',
            field=models.TextField(blank=True, help_text='\u5b66\u6821\u3001\u513f\u7ae5\u5165\u5b66\u7b49\u6559\u80b2\u60c5\u51b5', null=True, verbose_name='\u6e38\u5386\u5730\u6559\u80b2'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='geography',
            field=models.TextField(blank=True, help_text='\u81ea\u7136\u5730\u7406\u3001\u98ce\u666f\u3001\u81ea\u7136\u707e\u5bb3\u60c5\u51b5', null=True, verbose_name='\u81ea\u7136\u5730\u7406'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='history',
            field=models.TextField(blank=True, help_text='\u6e38\u5386\u8005\u542c\u95fb\u7684\u6e38\u5386\u5730\u5386\u53f2\u53d1\u5c55\u60c5\u51b5\u3001\u5927\u7684\u5386\u53f2\u4e8b\u4ef6\uff08\u5982\u6539\u571f\u5f52\u6d41\u7b49\uff09\u3001\u9057\u8ff9\u9057\u5740\u3001\u7891\u523b\u7b49', null=True, verbose_name='\u5386\u53f2'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='nation',
            field=models.TextField(blank=True, help_text='\u4eba\u53e3\u3001\u6c11\u65cf\u7b49\u60c5\u51b5', null=True, verbose_name='\u6e38\u5386\u5730\u6c11\u65cf'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='other',
            field=models.TextField(blank=True, help_text='\u5176\u4ed6\u91cd\u8981\u4fe1\u606f', null=True, verbose_name='\u5176\u4ed6'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='police',
            field=models.TextField(blank=True, help_text='\u653f\u6cbb\u3001\u519b\u4e8b\u3001\u6cbb\u5b89\u7b49\u60c5\u51b5', null=True, verbose_name='\u6e38\u5386\u5730\u6cbb\u5b89'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='religion',
            field=models.TextField(blank=True, help_text='\u5b97\u6559\u4fe1\u4ef0\u60c5\u51b5\u3001\u5b97\u6559\u653f\u7b56\u3001\u5bfa\u5e99\u548c\u6559\u5802\u3001\u5b97\u6559\u827a\u672f\u7b49', null=True, verbose_name='\u5b97\u6559'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='transportation',
            field=models.CharField(blank=True, help_text='\u6e38\u5386\u8005\u7684\u4ea4\u901a\u65b9\u5f0f\uff1a\u706b\u8f66\u3001\u8f6e\u8239\u3001\u9a6c\u3001\u6b65\u884c\u7b49', max_length=1000, null=True, verbose_name='\u4ea4\u901a\u65b9\u5f0f'),
        ),
    ]
