# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-26 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himalaya', '0024_auto_20170426_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='Pubvolume',
            field=models.CharField(help_text='\u6240\u5728\u520a\u7269\u5377\u671f', max_length=1000, null=True, verbose_name='\u520a\u7269\u5377\u671f'),
        ),
    ]
