# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-27 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himalaya', '0027_auto_20170427_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='Pubvolume',
            field=models.CharField(blank=True, help_text='\u6240\u5728\u520a\u7269\u5377\u671f', max_length=1000, null=True, verbose_name='\u520a\u7269\u5377\u671f'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='pageNum',
            field=models.CharField(blank=True, help_text='\u6240\u5728\u520a\u7269\u7684\u9875\u7801', max_length=1000, null=True, verbose_name='\u6240\u5728\u520a\u7269/\u6c47\u7f16\u9875\u7801'),
        ),
    ]
