# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-09 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himalaya', '0028_auto_20170427_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='Pubvolume',
        ),
        migrations.AlterField(
            model_name='booklist',
            name='Publication',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u51fa\u7248\u520a\u7269'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='author',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='bNameCH',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u8457\u4f5c\u540d\u79f0\uff08CH\uff09'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='bNameEN',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u8457\u4f5c\u540d\u79f0\uff08EN\uff09'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='bookID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='\u4e66\u76eeID'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='dopub',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u520a\u7269\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='nationality',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u4f5c\u8005\u56fd\u522b'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='\u9898\u89e3'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='pageNum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6240\u5728\u520a\u7269\u9875\u7801'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='press',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='\u51fa\u7248\u793e'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='pubdate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u51fa\u7248\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='translator',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u8bd1\u8005'),
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='subjecttype',
            field=models.IntegerField(blank=True, default=-1, editable=False, verbose_name='\u4e13\u9898\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='route',
            name='RouteName',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u7ebf\u8def\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='route',
            name='RoutePer',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u6e38\u5386\u4eba'),
        ),
        migrations.AlterField(
            model_name='route',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='\u7eac\u5ea6'),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='\u7ecf\u5ea6'),
        ),
        migrations.AlterField(
            model_name='site',
            name='sitenameCH',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u5730\u70b9'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='DataPage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6570\u636e\u9875\u7801'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='agriculture',
            field=models.TextField(blank=True, null=True, verbose_name='\u6e38\u5386\u5730\u519c\u4e1a'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='custom',
            field=models.TextField(blank=True, null=True, verbose_name='\u98ce\u4fd7\u6587\u5316'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='economy',
            field=models.TextField(blank=True, null=True, verbose_name='\u6e38\u5386\u5730\u7ecf\u6d4e'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='\u6e38\u5386\u5730\u6559\u80b2'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='geography',
            field=models.TextField(blank=True, null=True, verbose_name='\u81ea\u7136\u5730\u7406'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='\u5386\u53f2'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='nation',
            field=models.TextField(blank=True, null=True, verbose_name='\u6e38\u5386\u5730\u6c11\u65cf'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='\u5176\u4ed6'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='police',
            field=models.TextField(blank=True, null=True, verbose_name='\u6e38\u5386\u5730\u6cbb\u5b89'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='religion',
            field=models.TextField(blank=True, null=True, verbose_name='\u5b97\u6559'),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='transportation',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u4ea4\u901a\u65b9\u5f0f'),
        ),
    ]
